# syntax = docker/dockerfile:experimental
# Build Container
FROM golang:1.13.5 as kanban-replicator-builder

ENV GO111MODULE on
WORKDIR /go/src/bitbucket.org/latonaio

COPY go.mod .

RUN go mod download

COPY . .

RUN go build -o kanban-replicator ./cmd/kanban-replicator


# Runtime Container
FROM alpine:3.12

RUN apk add --no-cache libc6-compat

ENV SERVICE=kanban-replicator \
    POSITION=BackendService \
    AION_HOME="/var/lib/aion" \
    APP_DIR="${AION_HOME}/${POSITION}/${SERVICE}"

RUN mkdir -p ${AION_HOME}/Data
WORKDIR ${AION_HOME}

COPY --from=kanban-replicator-builder /go/src/bitbucket.org/latonaio/kanban-replicator .

CMD ["./kanban-replicator", "-c", "config/project.yml"]
