# syntax = docker/dockerfile:experimental
# Build Container
FROM golang:1.13.5 as service-broker-builder

ENV GO111MODULE on
WORKDIR /go/src/bitbucket.org/latonaio

COPY go.mod .

RUN go mod download

COPY . .

RUN go build -o service-broker ./cmd/service-broker


# Runtime Container
FROM alpine:3.12

RUN apk add --no-cache libc6-compat

ENV SERVICE=service-broker \
    POSITION=BackendService \
    AION_HOME="/var/lib/aion" \
    APP_DIR="${AION_HOME}/${POSITION}/${SERVICE}"

RUN mkdir -p ${AION_HOME}/Data
WORKDIR ${AION_HOME}

COPY --from=service-broker-builder /go/src/bitbucket.org/latonaio/service-broker .

CMD ["./service-broker", "-d", "-c", "config/project.yml"]
